/*
┌──────────────────────────────────────────────────────────────────┐
│  Author: Ivan Murzak (https://github.com/IvanMurzak)             │
│  Repository: GitHub (https://github.com/IvanMurzak/Unity-MCP)    │
│  Copyright (c) 2025 Ivan Murzak                                  │
│  Licensed under the Apache License, Version 2.0.                 │
│  See the LICENSE file in the project root for more information.  │
└──────────────────────────────────────────────────────────────────┘
*/

#nullable enable

namespace com.IvanMurzak.Unity.MCP.Common.Model
{
    public class ResponsePromptMessage
    {
        /// <summary>
        /// Gets or sets the content of the message, which can be text, image, audio, or an embedded resource.
        /// </summary>
        /// <remarks>
        /// The <see cref="Content"/> object contains all the message payload, whether it's simple text,
        /// base64-encoded binary data (for images/audio), or a reference to an embedded resource.
        /// The <see cref="ContentBlock.Type"/> property indicates the specific content type.
        /// </remarks>
        public ContentBlock Content { get; set; } = new ContentBlock()
        {
            Type = string.Empty
        };

        /// <summary>
        /// Gets or sets the role of the message sender, specifying whether it's from a "user" or an "assistant".
        /// </summary>
        /// <remarks>
        /// In the Model Context Protocol, each message must have a clear role assignment to maintain
        /// the conversation flow. User messages represent queries or inputs from users, while assistant
        /// messages represent responses generated by AI models.
        /// </remarks>
        public Role Role { get; set; } = Role.User;

        public ResponsePromptMessage() { }

        public ResponsePromptMessage(string message, Role role)
        {
            Content = new ContentBlock
            {
                Type = "text",
                Text = message,
                MimeType = Consts.MimeType.TextPlain
            };
            Role = role;
        }
    }
}
